# Generated by Django 5.1.7 on 2025-04-01 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artikeln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20, unique=True)),
                ('beschreibung', models.TextField()),
                ('picture', models.ImageField(upload_to='artikeln/')),
                ('preis', models.CharField(max_length=20)),
                ('saving', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=255)),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artikel', to='products.kategorie')),
            ],
        ),
    ]
